set(ORBIS 1)

set(CMAKE_SHARED_LIBRARY_PREFIX lib)
set(CMAKE_SHARED_LIBRARY_SUFFIX .prx)
set(CMAKE_SHARED_MODULE_PREFIX lib)
set(CMAKE_SHARED_MODULE_SUFFIX .prx)
set(CMAKE_IMPORT_LIBRARY_PREFIX lib)
set(CMAKE_IMPORT_LIBRARY_SUFFIX _stub_weak.a)
set(CMAKE_EXECUTABLE_SUFFIX .elf)

set(CMAKE_DL_LIBS "")

set(CMAKE_FIND_LIBRARY_PREFIXES lib)
set(CMAKE_FIND_LIBRARY_SUFFIXES .a _stub_weak.a)
